### ISSUE TITLE
Signatures not checked due to missing keys

### ISSUE THREAD

**Issue by cameronphillips09** [mko-x/katoolin#1]
**I posted this originally in the V1 issues because I started using that version before updating to V2.**

I am using a Raspberry Pi 3+ with Raspbian in a class at school and thought a good addition would be the Kali packs. I can get to "What do you want to do?> 1 (Add kali Linux repositories)

> Executing: /tmp/apt-key-gpghome.cByaDc33hs/gpg.1.sh --keyserver pool.sks-keyservers.net --recv-keys ED444FF07D8D0BF6
> gpg: key ED444FF07D8D0BF6: 163 signatures not checked due to missing keys
> gpg: key ED444FF07D8D0BF6: "Kali Linux Repository devel@kali.org" not changed
> gpg: Total number processed: 1
> gpg: unchanged:1

I had a few other issues to get to this point.
I had to install dirmngr, and wget -q -O - archive.kali.org/archive-key.asc | apt-key add from [https://github.com/LionSec/katoolin/issues/178](url) 
I also tried install V2 from post [https://github.com/LionSec/katoolin/issues/157](url)
I have been playing with Linux for a while, but have never gone too deep with it so I may be missing something simple.
Any ideas would be greatly appreciated.

**Comment by mko-x** [comment]
Hi @cameronphillips09 ,

we will get that running. Just some questions:

Which version of Raspbian are you using?

Try the following methods and put the output information in your answer.
```bash
cat /etc/os-release
lsb_release -a
hostnamectl
```

After that find out your kernel currently running ( just so we know):
```bash
uname -a
```

Please paste the contents of your "/etc/apt/sources.list" before and after runnng the katoolin install. You can strip it regarding katoolin.

And finally please paste the output of 
```bash
apt-key list
```
before and after katoolin install. You can strip it regarding katoolin, too.

I will investigate if I have more info.

**Comment by mko-x** [comment]
Even if you are not able to proof it yet - should be now.
